version: '3.8'

services:
  api:
    image: nguyenthieng0106/login-service
    container_name: loginApi
    restart: unless-stopped
    ports:
      - '9999:9999'
    env_file:
      - .env
    networks:
      - loginService
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - loginService

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - loginService

networks:
  loginService:
