# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD To EC2

# Cancel previous runs that are not completed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create Env file
        run: |
          touch .env
          echo "${{ secrets.PROD_ENV }}" > .env

          cat .env

      - name: restart server
        run: pm2 restart login-service

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: nguyenthieng0106/login-service
      #     tags: |
      #       type=raw,value={{date 'YYYY-MM-DD'}}

      # - name: Deploy
      #   run: |
      #     cd /home/ubuntu/actions-runner/_work/login-service/login-service
      #     sudo chmod +x deploy.sh
      #     sh deploy.sh nguyenthieng0106/login-service ${{ steps.meta.outputs.tags }}
